name: CI

on:
  - push
  - pull_request
  - workflow_dispatch  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pandoc
        run: |
          # Install pandoc using apt
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Clone and install d2l-book
        run: |
          git clone https://github.com/openmlsys/d2l-book.git
          cd d2l-book
          pip install .

      - name: Build HTML documentation
        run: |
          source venv/bin/activate
          d2lbook build html