name: D2l Test

on:
  - push
  - pull_request
  - workflow_dispatch  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: s-weigand/setup-conda@v1
        name: Set up Conda environment

      - run: |
          conda config --append channels conda-forge
          conda create -n py38 python=3.8 -y  # Create and activate Python 3.8 environment
          conda activate py38
          conda install -y pandoc==2.17

      - run: conda activate py38 && pip install -r requirements.txt

      - run: |
          git clone https://github.com/openmlsys/d2l-book.git
          cd d2l-book
          pip install .  # Install the package from the cloned repo
          
      - run: d2lbook build html  # Build HTML documentation
