name: Update Docs

on:
  - push
  - pull_request
  - workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Cache Python packages to speed up builds
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      # Install Pandoc using apt-get
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      # Install Python dependencies and build the HTML documentation
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx-mathjax-offline
          git clone https://github.com/openmlsys/d2l-book.git
          cd d2l-book
          pip install .
          cd ..
          sh build_html.sh

      # Clone the html-en repository
      - name: Clone html-en Repository
        run: |
          git clone https://github.com/openmlsys/html-en.git
          cp -r _build/html/* html-en/

      # Commit and push the updated docs
      - name: Commit and Push Changes
        run: |
          cd html-en
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Commit only if there are changes
          git diff --quiet || git commit -m 'Update English docs'
          # Push changes if there are any
          git push || echo "No changes to push"
