name: Update Docs
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx-mathjax-offline
          git clone https://github.com/openmlsys/d2l-book.git
          cd d2l-book
          pip install .
          cd ..
          sh build_html.sh
      - run: cd ..
      # Modified these steps for proper authentication
      - name: Clone and push to html-en
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/openmlsys/html-en.git
          cp -r _build/html/* html-en/
          cd html-en
          git config user.name "Chivier"
          git config user.email "chivier.humber@outlook.com"
          git add .
          git commit -m 'update docs'
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/openmlsys/html-en.git main