name: Update Docs

on:
  - push
  - pull_request
  - workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Python 3.8
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      # Install Pandoc using apt-get
      - run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      # Install Python dependencies and build the HTML documentation
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx-mathjax-offline
          git clone https://github.com/openmlsys/d2l-book.git
          cd d2l-book
          pip install .
          cd ..
          sh build_html.sh

      # Clone the html-en repository
      - run: cd ..
      - run: |
          git clone https://github.com/openmlsys/html-en.git
      - run: cp -r _build/html/* html-en/
      - run: |
          cd html-en 
          git add .
          git config user.name "Chivier"
          git config user.email "chivier.humber@outlook.com"
          git commit -m 'update docs'
          git push https://$PAT_TOKEN@github.com/openmlsys/html-en.git HEAD:main
