
name: CI

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
      - run: conda config --append channels conda-forge
      - run: conda install -y python=3.8
      - run: python3.8 -m pip install -r requirements.txt
      - run: conda install -y pandoc==2.17
      - run: pip install sphinx-mathjax-offline

      - run: |
          git clone https://github.com/openmlsys/d2l-book.git
          cd d2l-book
          python3.8 -m pip install .
      - run: sh build_html.sh
      - run: cd ..
      - run: git clone https://github.com/openmlsys/html-en.git
      - run: cp -r openmlsys-en/_build/html/*  html-en/
      - run: |
          cd html-en
          git add .
          git commit -m 'update english docs'
          git push
         
          
      
